# Dependencies
highlighter:      rouge
        
# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Grey Luo
tagline:          'Growing Software Engineer/Data Scientist. Machine Learning Enthusiast.'
description:      'Growing Software Engineer/Data Scientist. Machine Learning Enthusiast.'
url:              www.luofeithu.com
baseurl:          /

author:
  name:           'Fei(Grey) Luo'
  url:            https://github.com/luofei11

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/luofei11

# Collections
collections:
  projects:
  experiences:
